---
 - name: Configure Redis servers
  hosts: server_role_redis_server
  become: true
  gather_facts: yes
  remote_user: rocky
  roles:
    - redis

 - name: Configure Frontend servers
  hosts: server_role_frontend_server
  become: true
  gather_facts: yes
  remote_user: ubuntu
  roles:
    - frontend
